config/urls.py
from django.apps import apps
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('core/', include('core.urls')),
    path('ex/', include('ex_form.urls')),
]

# if settings.DEBUG:
if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
    path("", TemplateView.as_view(template_name='core/root.html'), name='root'),
    path("root/", TemplateView.as_view(template_name='core/root1.html'), name='root1'),
]

core/models.py
from django.db import models

# Create your models here.

core/views.py
from django.shortcuts import render

# Create your views here.

templates/core/base.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>장고 프로젝트!</title>

</head>
<body>
    <header class="p-3 bg-dark text-white">
        <div class="container">
          <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
            <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none">
              <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
            </a>
    
            <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
              <li><a href="#" class="nav-link px-2 text-secondary">Home</a></li>
            </ul>
    
            <form class="col-12 col-lg-auto mb-3 mb-lg-0 me-lg-3">
              <input type="search" class="form-control form-control-dark" placeholder="Search..." aria-label="Search">
            </form>
    
            <div class="text-end">
              <button type="button" class="btn btn-outline-light me-2">Login</button>
              <button type="button" class="btn btn-warning">Sign-up</button>
            </div>
          </div>
        </div>
      </header>
    <main class="py-5">
        <div class='container'>
            {% block content %}{% endblock  %}
        </div>
    </main>
<main>
    <div class="container-sm">100% wide until small breakpoint</div>
    <div class="container-md">100% wide until medium breakpoint</div>
    <div class="container-lg">100% wide until large breakpoint</div>
    <div class="container-xl">100% wide until extra large breakpoint</div>
    <div class="container-xxl">100% wide until extra extra large breakpoint</div>
</main>
<footer class="text-body-secondary py-5">
    <div class="container">
        &copy; 파이썬
    </div>
</footer>
</body>
</html>

templates/core/base1.html
{% load static %}
<!doctype html>
<html lang="ko">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>

  <body class="bg-dark">

    <!-- 네비게이션바 시작 -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light my-1 sm">
        <div class="container-fluid w-75 p-3 style="background-color: #eee;"">
            <a class="navbar-brand" href="#">My Stock</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse py-5 container-sm" id="navbarNav">
                <ul class="navbar-nav me-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'core:root' %}">주식 정보1</a>
                    </li>
                    <!-- 다른 메뉴 항목 추가 가능 -->
                </ul>
                
                <!-- 로그인 양식 -->
                {% comment %} <form class="d-flex" method="POST" action="{% url 'login' %}"> {% endcomment %}
                <form class="d-flex" method="POST" action="#">
                    {% csrf_token %}
                    {% comment %} <input class="form-control me-2" type="text" name="username" placeholder="Username" aria-label="Username" required>
                    <input class="form-control me-2" type="password" name="password" placeholder="Password" aria-label="Password" required> {% endcomment %}
                    <a href="#" class="btn btn-outline-success" data-bs-toggle="offcanvas" type="submit">로그인</button>
                    <a href="#" class="btn btn-outline-danger" type="submit">회원가입</button>
                </form>
            </div>
        </div>
    </nav>
    <!-- 네비게이션바 끝 -->

    <div class="container mt-4">
        {% block content %}
        {% endblock %}
    </div>


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/core/root.html
{% extends "core/base.html" %}
{% block content %}
    root.html 1
{% endblock %}

templates/core/root1.html
{% extends "core/base1.html" %}
{% block content %}
    root.html 부트스트랩
{% endblock %}