config/urls.py
from django.apps import apps
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from dashboard import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('dashboard/', include('dashboard.urls')),
    path('core/', include('core.urls')),
    path('ex/', include('ex_form.urls')),
]

# if settings.DEBUG:
if apps.is_installed("debug_toolbar"):
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
    ]

core/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "core"

urlpatterns = [
    path("", TemplateView.as_view(template_name='core/root.html'), name='root'),
    path("root/", TemplateView.as_view(template_name='core/root1.html'), name='root1'),
]

ex_form/urls.py
from django.urls import path, include
from . import views

app_name = 'ex_form'

urlpatterns = [
    path('', view=views.index, name='index'),
    path('extendtest', view=views.extendtest, name='extendtest'),
    path('exam01/', view=views.exam01, name='exam01'),
    path('exam02/', view=views.exam02, name='exam02'),
    path('exam03/', view=views.exam03, name='exam03'),
    path('stocks/', view=views.stock_list, name='stock_list'),
    # path('', view=views.index, name='index'),
    # 클래스형 뷰
    path('exam04/', view=views.Myview1.as_view(), name='exam04'),
    path('exam05/', view=views.Myview2.as_view(), name='exam05'),
    path('exam06/', view=views.Myview3.as_view(), name='exam06'), # formview 저장하진 않아.
    path('exam07/', view=views.Myview4.as_view(), name='exam07'), # Createview
    path('exam08/<int:pk>', view=views.Myview5.as_view(), name='exam08'), # Detailview
    path('exam09/', view=views.Myview6.as_view(), name='exam09'), # Listview
    path('exam10/<int:pk>/', view=views.Myview7.as_view(), name='exam10'), # Updateview
]

ex_form/models.py
from django.db import models

# Create your models here.
class Person(models.Model):
    name = models.CharField(max_length=20, null=False)
    age= models.IntegerField(null=False)
    
    def __str__(self):
        return f"Person[id={self.pk} name={self.name}, age={self.age}]"
    
class MyStock(models.Model):
    code = models.CharField(max_length=7)
    name = models.CharField(max_length=20)
    reasons = models.TextField()
    
    def __str__(self):
        return f"MyStock[{self.name} ({self.code}) {self.reasons}]"

ex_form/forms.py
from django import forms
from django.core.validators import MaxLengthValidator, MinLengthValidator
from .models import Person

class PersonForm(forms.Form):
    name = forms.CharField(
        label='이름',
        max_length=20,
        required=True,
        validators=[
            MaxLengthValidator(limit_value=20),
            MinLengthValidator(limit_value=4)
        ]
        )
    age = forms.IntegerField(label='나이', required=True)
    

class PersonModelForm(forms.ModelForm):
    class Meta:
        model = Person
        fields = ['name','age']
    


CATEGORY_CHOICES = [
    ('new_bra', 'new_bra'),
    ('3w', '3w'),
    ('consen', 'consen'),
    ('sun', 'sun'),
]

class StockFilterForm(forms.Form):
    new_bra = forms.BooleanField(label='new_bra', required=False)
    w3 = forms.BooleanField(label='w3', required=False)
    consen = forms.BooleanField(label='consen', required=False)
    sun = forms.BooleanField(label='sun', required=False)
    

ex_form/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .forms import PersonForm, PersonModelForm
from django.db.models import Q
from .models import Person, MyStock
from .forms import StockFilterForm
from django.views.generic import View
from django.views.generic import FormView, CreateView, DetailView, ListView, UpdateView

def extendtest(request):
    return render(request, 'ex_form/base.html')


class Myview7(UpdateView):
    model = Person
    form_class = PersonModelForm
    # template_name = 'ex_form/person_form'
    success_url = '/ex/exam09'

class Myview6(ListView):
    model = Person
    


class Myview5(DetailView):
    model = Person
    # template_name= 'ex_form/person_detail.html'  ## app/ model명 _ detail.html



class Myview4(CreateView):
    model = Person
    form_class = PersonModelForm
    template_name = 'ex_form/exam05_form.html'
    success_url = '/ex/'



class Myview3(FormView):
    form_class = PersonModelForm
    template_name = 'ex_form/exam05_form.html'
    success_url = '/ex/'

    def form_valid(self, form):
        print('데이터가 유효하면')
        m = Person(**form.cleaned_data)
        m.save()
        return super().form_valid(form)

class Myview2(View):
    form_class = PersonForm
    initial = {
        'name':'이름',
        'age':0
    }
    template_name = 'ex_form/exam05_form.html'
    
    def get(self, request):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form':form})
    
    
    def post(self, request):
        form = PersonModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ex_form:index')
    
        return render(request, 'ex_form/exam04_form.html', {'form':form})

class Myview1(View):
    
    def get(self, request):
        form = PersonModelForm()
        return render(request, 'ex_form/exam04_form.html', {'form':form})
    
    def post(self, request):
        form = PersonModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('ex_form:index')
    
        return render(request, 'ex_form/exam04_form.html', {'form':form})
            

# Create your views here.
def index(request):
    return render(request, 'ex_form/index.html')

def exam01(request):
    print('exam01')
    if request.method == "POST":
        name = request.POST['name']
        age = request.POST['age']
        print('요청 처리', name, age)
        Person(name=name, age=age).save()
        return HttpResponse('처리완료')
    else:
        return render(request, 'ex_form/exam01_form.html')


def exam02(request):
    print('exam02')
    if request.method == 'POST':
        personForm = PersonForm(request.POST)
        if personForm.is_valid(): # 유효성을 검증 
            name = personForm.cleaned_data['name']
            age = personForm.cleaned_data['age']
            Person(name=name, age=age).save()
            return HttpResponse('처리완료')
        else:
            return render(
                request,
                'ex_form/exam02_form.html',
                {'form': personForm}
            )
    else:
        form = PersonForm()
        print(form)
        return render(request, 'ex_form/exam02_form.html', {'form':form})




from .forms import PersonModelForm
def exam03(request):
    print('exam03')
    if request.method == 'POST':
         form = PersonModelForm(request.POST)
         if form.is_valid():
            form.save()
            return HttpResponse('처리완료')

    else:
        form = PersonModelForm()
    
    return render(request, 'ex_form/exam03_form.html', {'form':form})


def stock_list(request):
    
    category_filters = []
    mystocks = MyStock.objects.all()
    if request.method == 'POST':
        form = StockFilterForm(request.POST)
        if form.is_valid():
            if form.cleaned_data.get('new_bra'):
                category_filters.append('new_bra')
            if form.cleaned_data.get('3w'):
                category_filters.append('3w')
            if form.cleaned_data.get('sun'):
                category_filters.append('sun')
            if form.cleaned_data.get('consen'):
                category_filters.append('consen')
            
            if category_filters:
                query = Q()
                for category in category_filters:
                    query &= Q(reasons__icontains=category)
                mystocks = mystocks.filter(query)
                print('필터되서 rendering!!')
            else:
                print('전체데이터')
            return render(request, "ex_form/stock_list.html", {"form":form, 'mystocks':mystocks})
                
        else:
            print('is_valid failed! ')
            return render(request, "ex_form/stock_list.html", {"form":form, 'mystocks':mystocks})
    else:
        form = StockFilterForm()
        print('그냥 rendering!!')
        print("category_filters",category_filters)
        return render(request, "ex_form/stock_list.html", {"form":form, 'mystocks':mystocks}) 
    

templates/ex_form/_headers.html
<header>
    <div class="px-3 py-2 text-bg-dark border-bottom">
      <div class="container">
        <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
          <a href="/" class="d-flex align-items-center my-2 my-lg-0 me-lg-auto text-white text-decoration-none">
            <svg class="bi me-2" width="40" height="32" role="img" aria-label="Bootstrap"><use xlink:href="#bootstrap"></use></svg>
          </a>

          <ul class="nav col-12 col-lg-auto my-2 justify-content-center my-md-0 text-small">
            <li>
              <a href="#" class="nav-link text-secondary">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#home"></use></svg>
                Home
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#speedometer2"></use></svg>
                Dashboard
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#table"></use></svg>
                Orders
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#grid"></use></svg>
                Products
              </a>
            </li>
            <li>
              <a href="#" class="nav-link text-white">
                <svg class="bi d-block mx-auto mb-1" width="24" height="24"><use xlink:href="#people-circle"></use></svg>
                Customers
              </a>
            </li>
          </ul>
        </div>
      </div>
    </div>
    <div class="px-3 py-2 border-bottom mb-3">
      <div class="container d-flex flex-wrap justify-content-center">
        <form class="col-12 col-lg-auto mb-2 mb-lg-0 me-lg-auto" role="search">
          <input type="search" class="form-control" placeholder="Search..." aria-label="Search">
        </form>

        <div class="text-end">
          <button type="button" class="btn btn-light text-dark me-2">Login</button>
          <button type="button" class="btn btn-primary">Sign-up</button>
        </div>
      </div>
    </div>
  </header>

templates/ex_form/base.html
{% extends "ex_form/root.html" %}

{% comment %} <div class="container"> {% endcomment %}
{% block content%}

    <div class="row justify-content-md-center" id=''>
        {% block header %}
            {% include "ex_form/_headers.html" %}
        {% endblock header %}
    </div>

    <div class="row justify-content-md-center">
        <div class="col-sm-4 ">
            <div class="row">
                {% block left_top %}left_top{% endblock left_top %}
            </div>
            <div class="row">
                {% block left_bottom %}left_bottom{% endblock left_bottom %}
            </div>
                        
        </div>
        <div class="col-md-auto">
            {% block right %}right{% endblock right %}
        </div>
    </div>
    <div class="row justify-content-md-center">
        {% block footer %}footer{% endblock footer %}
    </div>
{% endblock %}
{% comment %} </div> {% endcomment %}

templates/ex_form/exam01_form.html
<form method='post'>
    {% csrf_token %}
    이름:<input type='text' name='name'><br>
    나이:<input type='text' name='age'><br>
    <input type='submit' value='전송'><br>
</form>

templates/ex_form/exam02_form.html
<form method='post'>
    {% csrf_token %}
    
    {{ form }}
    <input type='submit' value='전송'><br>
</form>
<hr>
<form method='post'>
    {% csrf_token %}
    <table>
        {{ form }}
    </table>
    <input type='submit' value='전송'><br>
</form>
<form method='post'>
    {% csrf_token %}
    <table>
        {{ form.as_ul }}
    </table>
    <input type='submit' value='전송'><br>
</form>

templates/ex_form/exam03_form.html
{{ form.errors }}
<form method='post'>
    {% csrf_token %}
    {{ form }}
    
    <input type='submit' value='전송'><br>

templates/ex_form/exam04_form.html
<p> exam04_form.html </p>
<form method='post'>
    {% csrf_token %}
    {{ form }}
    
    <input type='submit' value='전송'><br>

templates/ex_form/exam05_form.html
<p> exam04_form.html </p>
<form method='post'>
    {% csrf_token %}
    {{ form }}
    
    <input type='submit' value='전송'><br>

templates/ex_form/index.html
{% extends "ex_form/base.html" %}
{% block right %}
<div class="btn-group" role="group" aria-label="Basic checkbox toggle button group">
    <input type="checkbox" class="btn-check" id="btncheck1" autocomplete="off">
    <label class="btn btn-outline-primary" for="btncheck1">Checkbox 1</label>
  
    <input type="checkbox" class="btn-check" id="btncheck2" autocomplete="off">s
    <label class="btn btn-outline-primary" for="btncheck2">Checkbox 2</label>
  
    <input type="checkbox" class="btn-check" id="btncheck3" autocomplete="off">
    <label class="btn btn-outline-primary" for="btncheck3">Checkbox 3</label>
  </div>

  <div class="container-fluid bg-danger my-5"> 
    <p>안녕하셍 ㅛ div 태그입다.</p>
   </div>

<ul class="list-group">
    <li class="list-group-item"><a href="{% url 'ex_form:exam01' %}"> exam01</a></li>
    <li class="list-group-item"><a href="{% url 'ex_form:exam02' %}"> exam02</a></li>
    <li class="list-group-item"><a href="{% url 'ex_form:exam03' %}"> exam03</a></li>
    <li class="list-group-item"><a href="{% url 'ex_form:exam04' %}"> exam04</a></li>
    <li class="list-group-item"><a href="{% url 'ex_form:exam05' %}"> exam05</a></li>
    <li class="list-group-item"><a href="{% url 'ex_form:exam06' %}"> exam06</a></li>
    <li class="list-group-item"><a href="{% url 'ex_form:exam07' %}"> exam07</a></li>
    {% comment %} <li class="list-group-item"><a href="{% url 'ex_form:exam08:1' %}"> exam08</a></li> {% endcomment %}
    <li class="list-group-item"><a href="{% url 'ex_form:exam09' %}"> exam09</a></li>
    {% comment %} <li class="list-group-item"><a href="{% url 'ex_form:exam10' %}"> exam10</a></li> {% endcomment %}
</ul>
{% endblock  %}

templates/ex_form/person_detail.html
<p>person_detail.html</p>
{{ object }}

templates/ex_form/person_form.html
{% csrf_token %}
{{ form }}

templates/ex_form/person_list.html
<p>person_list.html</p>

{% for object in object_list %}
<a href={% url "ex_form:exam08" object.id %}> {{ object.name }}<a>
<a href={% url "ex_form:exam10" object.id %}> 수정 <a>
<br>
{% endfor %}

templates/ex_form/root.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
 <!-- Required meta tags -->
 <meta charset="utf-8">
 <meta name="viewport" content="width=device-width, initial-scale=1">

 <!-- Bootstrap CSS -->
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

 <title>장고 프로젝트!</title></head>
<body class="d-flex h-100 text-center text-white bg-dark">
    {% block content %}{% endblock  %}
</body>
</html>

templates/ex_form/stock_list.html
{% extends "ex_form/base.html" %}
{% block left_top %}
    <div class="form-check text-start">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-check mb-3">
                    {{ field }} 
                    <label class="form-check-label" for="{{ field.id_for_label }}">
                        {{ field.label }}  
                    </label>
                </div>
            {% endfor %}
            {% comment %} {{ form.as_p }} {% endcomment %}
            <button type="submit" class="btn btn-primary mb-3">Search</button>
        </form>
    </div>
{% endblock left_top %}    

{% block left_bottom %}
    
        {% if mystocks %}
            <ul class="list-unstyled fw-normal pb-2 small my-2">
                {% for stock in mystocks %}
                    {% comment %} <li class="list-group-item" >
                        <a href="">{{stock.name }}({{stock.code}})</a>
                    </li> {% endcomment %}
                    <p><a class="link-light text-decoration-none " href="#">{{stock.name}}</a></p>
                {% empty %}
                    <li class="list-group-item">No products found.</li>
                {% endfor %}
            
            </ul>
        {% endif %}
        <li class="list-group-item">No Data found.</li>
{% endblock left_bottom %}    